title: Jhoel A. Cortez Huanca
logo: /assets/img/FotopPerfil2.png
#description: Soy un ingeniero de software
#show_downloads: true
theme: jekyll-theme-minimal

# Redes sociales
social_links:
  - name: LinkedIn
    link: https://www.linkedin.com/in/jhoel-anibal-cortez-huanca-424031243


#plugins:
#  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll-feed

#seo:
#title: "Mi Portafolio"
#description: "Un portafolio simple usando Jekyll y GitHub Pages"
#author: "JC"

#sass:
#  style: compressed


