title: "Jhoel A. Cortez Huanca"
description: "Soy un ingeniero de software apasionado por la tecnología y el análisis de datos."
logo: /assets/img/FotopPerfil2.png

remote_theme: "nombre-del-repositorio/figs-jekyll-theme" # Reemplaza con el nombre exacto del tema
plugins:
  - jekyll-remote-theme # Asegúrate de que el plugin esté activo
